title: MozFest Planning
url: "https://mozillafestival.org/"
baseurl: "/"

email: mozopenness2018@googlegroups.com
twitter: mozfestopenness

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
destination: '_site'
relative_links:
  enabled:     true
  collections: true

collections:
  open:
    output: true
    permalink: /:collection/:month/:title

defaults:
  - scope:
      path: ""
      type: "open"
    values:
      layout: "space"

plugins:
  - jekyll-relative-links

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'

include:
  - '_pages'
  - '_open'
